# Generated by Django 4.1.3 on 2022-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_req',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
