# Generated by Django 4.1.3 on 2022-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0002_alter_task_time_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True),
        ),
    ]
