# Generated by Django 4.1.3 on 2022-12-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0004_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
