# Generated by Django 4.1.3 on 2022-12-08 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0009_alter_task_time_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_req',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 12, 50, 6, 635281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='task',
            name='do_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
