# Generated by Django 4.1.3 on 2022-12-08 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0010_remove_task_time_req_task_deadline_task_do_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 12, 52, 27, 264053, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
