# Generated by Django 4.1.2 on 2022-12-09 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0011_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 6, 9, 58, 77475, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
